name: Check Build Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are changes in the build files."
            echo "Please rebuild using `npm run build` and commit the changes."
            exit 1
          else
            echo "No changes detected in the build files."
          fi
